#!/bin/bash

# custom initialization goes here - runs outside of the dev container
# just before the container is launched but after the container is created

set -xe

# make the config folder for the shared bash-config feature
mkdir -p ${HOME}/.config/bash-config
