#!/bin/bash

# Custom initialization goes here if needed.
# Runs inside the dev container after the container is created

################################################################################
# When using docker we will not be root inside the container
# the following steps are then required
################################################################################

if [[ $USER != "root" ]] ; then
    # make sure the non-root user can interact with the rtems BSP and RSB
    sudo chown -R ${USER}:${USER} /rtems*/rsb /rtems*/rtems
fi

################################################################################
# Shell customizations for Generic IOC devcontainers
################################################################################

# pick a theme that does not cause completion corruption in zsh
sed -i $HOME/.zshrc -e 's/ZSH_THEME="devcontainers"/ZSH_THEME="dst"/'

# allow personalization of all devcontainers in this subdirectory
# by placing a .devcontainer_rc file in the workspace root
if [[ -f /workspaces/.devcontainer_rc ]] ; then
    source /workspaces/.devcontainer_rc
fi
